### PR TITLE
Improve fork

### PR DESCRIPTION
**Pull request by calebeby**
Lots of small changes to this fork, based on the requests in a client project

I recommend reviewing this PR by reviewing the commits individually

You can also review all of the non-prettier+eslint changes to the main script file [here](https://github.com/cloudfour/headsup.js/compare/824f6e5a67fa84b12621b045caf0f40e166f3586...cloudfour:7667d715e8eacc81b7a840c367c839dee3da1c79#diff-1fdf421c05c1140f6d71444ea2b27638)

Currently I'm not planning on setting up publishing to npm, because there is little benefit and it will take some time. That can be done in the future if we decide it is necessary.

### CODE REVIEW

**Comment by spaceninja** [comment]
It's hard to evaluate your changes because you renamed the file from `headsup.js` to `index.js`, which means there's no diff. Could you undo the renaming until after this PR?

**Comment by calebeby** [comment]
@spaceninja GitHub displays the individual commit diffs correctly. Even if I renamed it back, the full-PR diff wouldn't be very readable because nearly every line changed because I enabled prettier. I still can rename it back if you want, it's just that it won't be better than viewing the individual commits

**Comment by spaceninja** [comment]
Thanks for renaming, that helped a lot.

For future PRs, it can be helpful to do lint fixes first in a separate commit or PR to avoid confusing diffs like this.

@Paul-Hebert this is your baby so I'll leave final approval to you, but I don't see any reason not to merge this if you think it's good.

**Comment by calebeby** [comment]
@spaceninja I did separate the commits. The prettier changes are in this commit: https://github.com/cloudfour/headsup.js/pull/1/commits/55d1658ae7b1aa5ba5fc2b941ea0f9a531647898 and the eslint changes are in this commit: https://github.com/cloudfour/headsup.js/pull/1/commits/d647cf6bca171875484b19a117572a6ec34cd0b4

**Review by Paul-Hebert — APPROVED** [review]
Thanks @calebeby ! This looks good to me.

**Pull request merged**
